#!/bin/bash

# Script to process HTML files and highlight Swift code blocks using SplashHTMLGen
# Usage: ./process_swift_code.sh [directory]

# Also, this script was generated by repeatedly ramming my head against the wall 
# that is Claude AI. 
# It probably only works by accident.

set -e

# Check if SplashHTMLGen is available
if ! command -v SplashHTMLGen &> /dev/null; then
    echo "Error: SplashHTMLGen not found. Please install it first:"
    echo "git clone https://github.com/JohnSundell/Splash.git"
    echo "cd Splash && make install"
    exit 1
fi

# Set directory to process (default to current directory)
DIR="${1:-.}"

# Check if directory exists
if [ ! -d "$DIR" ]; then
    echo "Error: Directory '$DIR' does not exist"
    exit 1
fi

# Temporary files
TEMP_SWIFT=$(mktemp)
TEMP_HTML=$(mktemp)
TEMP_FILE=$(mktemp)

# Cleanup on exit
trap "rm -f $TEMP_SWIFT $TEMP_HTML $TEMP_FILE" EXIT

# Process each HTML file
find "$DIR" -name "*.html" -type f | while read -r html_file; do
    echo "Processing: $html_file"
    
    # Use awk to extract and process code blocks
    awk -v temp_swift="$TEMP_SWIFT" -v temp_html="$TEMP_HTML" -v temp_file="$TEMP_FILE" '
    BEGIN {
        inside_code = 0
        code_content = ""
        RS = "\r?\n"
        open_tag = "<pre><code class=\"language-swift\">"
        close_tag = "</code></pre>"
    }
    
    # Match opening tag
    $0 ~ open_tag {
        inside_code = 1
        code_content = ""
        
        # Check if opening tag exists
        open_pos = index($0, open_tag)
        if (open_pos > 0) {
            # Get everything after opening tag
            temp_line = substr($0, open_pos + length(open_tag))
            
            # Check if closing tag is on same line
            close_pos = index(temp_line, close_tag)
            if (close_pos > 0) {
                # Single line code block
                code_content = substr(temp_line, 1, close_pos - 1)
                
                # Write code to temp file
                print code_content > temp_swift
                close(temp_swift)
                
                # Process with SplashHTMLGen
                cmd = "SplashHTMLGen \"$(cat " temp_swift ")\" 2>/dev/null > " temp_html
                system(cmd)
                
                # Read the result
                highlighted = ""
                while ((getline line < temp_html) > 0) {
                    if (highlighted != "") highlighted = highlighted "\n"
                    highlighted = highlighted line
                }
                close(temp_html)
                
                # Replace the original code block with highlighted version
                before_code = substr($0, 1, open_pos - 1)
                after_pos = open_pos + length(open_tag) + close_pos - 1 + length(close_tag)
                after_code = substr($0, after_pos + 1)
                
                # Print the parts
                if (before_code != "") print before_code
                printf "%s", open_tag
                printf "%s", highlighted
                printf "%s", close_tag
                if (after_code != "") print after_code
                
                inside_code = 0
                next
            } else {
                # Multi-line code block starts - store the beginning, do not print yet
                code_content = temp_line "\n"
                line_before_code = substr($0, 1, open_pos - 1)
                next
            }
        }
    }
    
    # Inside multi-line code block
    inside_code == 1 {
        # Check if closing tag is on this line
        close_pos = index($0, close_tag)
        if (close_pos > 0) {
            # Closing tag found
            code_content = code_content substr($0, 1, close_pos - 1)
            line_after_code = substr($0, close_pos + length(close_tag))
            
            # Write accumulated code to temp file
            printf "%s", code_content > temp_swift
            close(temp_swift)
            
            # Process with SplashHTMLGen
            cmd = "SplashHTMLGen \"$(cat " temp_swift ")\" 2>/dev/null > " temp_html
            system(cmd)
            
            # Read the highlighted HTML
            highlighted = ""
            while ((getline line < temp_html) > 0) {
                if (highlighted != "") highlighted = highlighted "\n"
                highlighted = highlighted line
            }
            close(temp_html)
            
            # Print: line before code (if any) + opening tag + highlighted code + closing tag + line after code (if any)
            if (line_before_code != "") {
                print line_before_code
                printf "%s", open_tag
            } else {
                printf "%s", open_tag
            }
            printf "%s", highlighted
            printf "%s", close_tag
            if (line_after_code != "") print line_after_code
            
            inside_code = 0
            code_content = ""
            line_before_code = ""
            line_after_code = ""
            next
        } else {
            # Still inside code block, accumulate content - do not print
            code_content = code_content $0 "\n"
            next
        }
    }
    
    # Print all other lines as-is
    {
        print
    }
    ' "$html_file" > "$TEMP_FILE"
    
    # Replace original file with processed version
    mv "$TEMP_FILE" "$html_file"
    echo "  ✓ Completed"
done

echo "All files processed successfully!"